### ISSUE TITLE
Error npm run build

### ISSUE THREAD

**Issue by mattermoran** [ipfs-shipyard/ipfs-webui#613]
Hello. I'm trying to make a prod build but I get an error when i do yarn build or npm run build. Am I missing something?

```
yarn build
yarn run v1.3.2
$ NODE_ENV=production webpack
Hash: 9deb1d725e33aca0c377
Version: webpack 3.10.0
Time: 41847ms
                                 Asset       Size  Chunks                    Chunk Names
  912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  [big]  
  f4769f9bdb7466be65088239c12046d1.eot    20.1 kB          [emitted]         
 fa2772327f55d8198301fdb8bcfc8158.woff    23.4 kB          [emitted]         
  e18bbf611f2a2e43afc071aa2f4e1512.ttf    45.4 kB          [emitted]         
  89889688147bd7575d6327160d64e760.svg     109 kB          [emitted]         
  674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]         
af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]         
 fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]         
  b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]         
448c34a56d699c29117adc64c43affeb.woff2      18 kB          [emitted]         
  d768e931c2b0dadcf508290c70069171.png    15.8 kB          [emitted]         
  8f70e85e85c6a23c75c6862292d871c0.png    24.9 kB          [emitted]         
  5da47f31372103568f04118f8d7053f5.png      16 kB          [emitted]         
  735208c91b7b43c74e258505965a6cb4.png    15.8 kB          [emitted]         
  7c550f337e6126b155c8efcc98441540.png    15.7 kB          [emitted]         
                   ipfs-webui.0.3.0.js    2.86 MB       0  [emitted]  [big]  main
                  ipfs-webui.0.3.0.css     212 kB       0  [emitted]         main
                            index.html  267 bytes          [emitted]         
  [36] (webpack)/buildin/global.js 509 bytes {0} [built]
 [971] multi ./src/app/js/index.js 28 bytes {0} [built]
 [972] ./src/app/js/index.js 870 bytes {0} [built]
[1182] ./src/app/js/routes.js 2.36 kB {0} [built]
[1192] ./src/app/js/containers/app.js 7.81 kB {0} [built]
[1510] ./src/app/js/containers/files.js 2.23 kB {0} [built]
[2372] ./src/app/js/pages/connections.js 4.7 kB {0} [built]
[2381] ./src/app/js/pages/objects.js 6.84 kB {0} [built]
[2391] ./src/app/js/pages/bitswap.js 3.79 kB {0} [built]
[2393] ./src/app/js/pages/routing.js 2.91 kB {0} [built]
[2687] ./src/app/js/pages/config.js 2.47 kB {0} [built]
[2689] ./src/app/js/pages/logs.js 5.21 kB {0} [built]
[2690] ./src/app/js/containers/root.js 2.03 kB {0} [built]
[2691] ./src/app/js/store/configure-store.js 3.4 kB {0} [built] [failed] [1 error]
[2692] ./src/app/css/app.less 41 bytes {0} [built]
    + 2678 hidden modules

ERROR in ./node_modules/lodash-es/mixin.js
Module build failed: TypeError: Cannot read property 'node' of undefined
    at PluginPass.AssignmentExpression (/Users/alex/Desktop/webui/node_modules/@babel/plugin-proposal-decorators/lib/index.js:139:261)
    at newFn (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/visitors.js:223:21)
    at NodePath._call (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitMultiple (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:93:17)
    at TraversalContext.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:178:19)
    at Function.traverse.node (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitMultiple (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:93:17)
    at TraversalContext.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:178:19)
    at Function.traverse.node (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitMultiple (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:93:17)
    at TraversalContext.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:178:19)
    at Function.traverse.node (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:106:18)
 @ ./node_modules/lodash-es/lodash.js 2289:36-57
 @ ./src/app/js/containers/files-explorer.js
 @ ./src/app/js/containers/files.js
 @ ./src/app/js/routes.js
 @ ./src/app/js/index.js
 @ multi ./src/app/js/index.js

ERROR in ./node_modules/ipfs-api/src/swarm/peers.js
Module build failed: TypeError: Cannot read property 'node' of undefined
    at PluginPass.AssignmentExpression (/Users/alex/Desktop/webui/node_modules/@babel/plugin-proposal-decorators/lib/index.js:139:261)
    at newFn (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/visitors.js:223:21)
    at NodePath._call (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitMultiple (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:93:17)
    at TraversalContext.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:178:19)
    at Function.traverse.node (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitMultiple (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:93:17)
    at TraversalContext.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:178:19)
    at Function.traverse.node (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/alex/Desktop/webui/node_modules/@babel/traverse/lib/path/context.js:106:18)
 @ ./node_modules/ipfs-api/src/swarm/index.js 8:11-29
 @ ./node_modules/ipfs-api/src/utils/load-commands.js
 @ ./node_modules/ipfs-api/src/index.js
 @ ./src/app/js/components/ipfs.js
 @ ./src/app/js/pages/home.js
 @ ./src/app/js/routes.js
 @ ./src/app/js/index.js
 @ multi ./src/app/js/index.js
```

**Comment by hacdias** [comment]
Hello @mattermoran! Thanks for reporting this. Indeed, I'm getting the same error. Let me check.

**Comment by hacdias** [comment]
@mattermoran so, I downgraded Babel to the previous beta and fixed it in that version (https://github.com/ipfs-shipyard/ipfs-webui/commit/00eec2005b7847888ed44bfdf0a6e2b3da2a0f9a). Once Babel 7.0.0-beta0.36 is released I will update it again. Let's keep this open.

**Comment by mattermoran** [comment]
@hacdias Great! Thanks a lot
